### ISSUE TITLE
How to make switches optimistic?

### ISSUE THREAD

**Issue by ifeign** [amscanne/aqua-connect-local#3]
I'm trying to make a switch for AUX 2, which has a value of `0B` but when I activate the switch in HASS, it immediately resets to an off state, even though the command was successfully sent.

Here's an example of what I wrote for that particular switch

```yaml
switch:
  - platform: template
    switches:
      pool_aux2:
        friendly_name: "Pool Cleaner"
        value_template: "{{ states('sensor.pool_panel') is search(' +.[5EUe][^ ]*$') }}"
        turn_on:
          service: "rest_command.pool_panel"
          data:
            KeyId: "0B"
        turn_off:
          service: "rest_command.pool_panel"
          data:
            KeyId: "0B"
```

Here's the html from WNewSt.htm

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta content="text/html; charset=ISO-8859-1"
 http-equiv="content-type">
  <title></title>
</head>
<body>
        Aux2        xxx
     Turned On      xxx
TFSE4S333333xxx

</body>
</html>
```
